### PR TITLE
adds support for :first, and :last

### PR DESCRIPTION
**Pull request by bcoe**
- added support for :first and :last.
- added `cheerio-eq.wrap` which extends `cheerio` with `cheerio-eq` functionality.

### CODE REVIEW

**Comment by CoDEmanX** [comment]
Thumbs up, should go upstream!

**Comment by CoDEmanX** [comment]
I ran into an issue, not sure if it's cheerio-eq in general or this PR: custom filter functions don't work.

Example:

```
// get text of 1st element, whose text is not empty or whitespace only
$("p").filter(function(){return $(this).text().trim()}).first().text();
```

Error:

```
C:\Users\Public\Documents\iojs\node_modules\cheerio-eq\index.js:9
while (match = selector.match(regex)) {
                        ^
TypeError: undefined is not a function
```

**Comment by CoDEmanX** [comment]
cheerio-eq.wrap() breaks it apparently, but not sure how to fix it - any ideas?

**Comment by watson** [comment]
Hey everybody. Inspired by this PR (thanks a lot @bcoe!!) I've been wanting to make a more generic solution for a while that can support any number of advanced selectors. I've therefore taken the liberty to use some of the stuff from this PR to build the new module [cheerio-advanced-selectors](https://github.com/watson/cheerio-advanced-selectors).

Currently the module only adds support for the following custom selectors:
- `:first`
- `:last`
- `:eq()`

But you can easily extend it with support for other selectors - just open an issue or make a pull request  :smiley:

I've also added support for pre-compiling of selectors which will speed up those cases where you like to run the same selector on multiple HTML documents.

@CoDEmanX Thanks for taking the time to debug the wrap method. The issue you discovered is fixed in the cheerio-advanced-selectors module :smiley: 

I'm closing this PR and hoping everyone will find the new module more helpfull :smiley: 

Once again thanks for all your comments and help with this - especially to @bcoe for making this PR

**Pull request closed without merging**
